---
bibliography: megafired-california.bib
csl: ecosphere.csl
params:
  title: "Causes, characteristics, and consequences of California's extreme wildfire events"
  author: |
    Michael J. Koontz^1\*^,
    Malcolm P. North^2,3^,
    Amy DeCastro^4,5^,
    Jennifer K. Balch^5^,
    Andrew M. Latimer^3^
  affiliation: |
    ^1^Earth Lab, University of Colorado; Boulder, CO, USA  
    ^2^USFS Pacific Southwest Research Station; Mammoth Lakes, CA, USA
    ^3^Department of Plant Sciences, University of California; Davis, CA, USA
    ^4^National Center for Atmospheric Research; Boulder, CO, USA
    ^5^Department of Geography, University of Colorado; Boulder, CO, USA
  correspondence: |
    mikoontz@gmail.com
  keywords: |
    wildfire, megafire    
  date_generated: !r format(Sys.Date(), "%B %d, %Y")
  
geometry: margin=1in
header-includes:
  - \usepackage[left]{lineno}
  - \linenumbers
  - \usepackage{setspace}
  - \doublespacing
  - \DeclareUnicodeCharacter{200E}{}
  - \usepackage{caption}
  - \captionsetup[figure]{labelformat=empty}
  - \captionsetup[table]{labelformat=empty}

output: pdf_document
---

```{r setup, include = FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

# `r params$title`

`r params$author`

`r params$affiliation`

*^\*^Correspondence:* ``r params$correspondence``

*Keywords:* `r params$keywords`

Date report generated: `r params$date_generated`

## Abstract 

## Introduction

Increasing frequency of large fires in western U.S. [@dennison2014]
Increasing frequency of extreme fire conditions in California [@goss2020].
Increasing severity of fires in western US [@parks2020].
Increasing area burned [@abatzoglou2016; @williams2019]
Burned area is fundamentally limited way of characterizing wildfires, particularly extreme wildfire events [@kolden2020].

Clear link between fire activity and climate change, and a proposed link to extreme events. 

Important to understand extreme wildfire events, as they are likely to be societally impactful [@balch2018; Iglesias et al., 2021].

Some efforts exist, but still focus on size [@joseph2019].

Challenge of defining "extreme wildfire events", but can be done by considering fire behavior within the context of fire's controllability, but decoupled from the societal impact [@tedim2018].

Then we can further characterize drivers of these extremes, and under what conditions they can lead to disasters [@bowman2017].

Interactions between drivers can be especially important [@balch2018].
Notion of homogenization of conditions in space/time leading to more extreme behavior (continuous fuels, longer duration hot drought)
Consideration of positive feedback-driven events as its own category.

Fuel, topography, weather and their spatiotemporal nexus to describe different "taxa" of extreme wildfire events.



## Methods

### Characterize extreme wildfire events
FIRED dataset daily fire perimeters [@balch2020].
2000 fire events in California between 2001 and 2020.
MODIS active fire product (MCD14ML) [@giglio2016].
Fire radiative power (FRP) to fireline intensity on a 4x daily timestep, then classification of that day based on @tedim2018.
Classes 5, 6, and 7 considered "extreme wildfire events."
Fire radiative power to fire radiative energy (FRE) by integrating through time course of each event.
Additional characterization of "extreme" based on FRE due to smoke impact

### Causes of extreme wildfire events
Collate potential causes of extreme wildfire events (or perhaps of all events; might as well?)
Total fuel, fuel heterogeneity  
Max wind speed from nearby RAWS station  
VPD from ERA-5 or Gridmet [@abatzoglou2013]  
Wind alignment [@abatzoglou2013] with slope (National Elevation Dataset)  
Historic aridity from CWD? [@flint2013]  

### Characterize different taxa of extreme wildfire events, perhaps using PCA

### Consequences of extreme wildfire events
Spatial join with FRAP (https://frap.fire.ca.gov/frap-projects/fire-perimeters/) and MTBS [@eidenshink2007].
Simple stats on cost, lives lost, homes destroyed for each category of extreme wildfire events



## Results

Figures
1. Conceptual diagram of fuel, topography, weather factors (and how they interact) to drive extreme wildfire events  
1. Map of daily FIRED perimeter having active fire detections within it and delineation of fire head  
1. Distribution of fireline intensity for all California fires
1. Distribution of multivariate fuel, topography, climate conditions
1. 

Table
1. Akin to [@bowman2017] showing different categories of extreme wildfire events
1. Depending on how many are classified as "extreme", a table with the info joined from MTBS/FRAP


## Discussion

Wildfire disasters versus extreme wildfire events.

## Acknowledgements


## Author contributions

Author contributions are defined using the Contributor Roles Taxonomy (CRediT; https://casrai.org/credit/).
Conceptualization: ; Data curation: ; Formal analysis: ; Funding acquisition: ; Investigation: ; Methodology: ; Project administration: ; Resources: ; Software: ; Supervision: ; Validation: ; Visualization: ; Writing -- original draft: ; Writing -- review and editing:   

\newpage

## References